Perl-Critic/Perl-Critic

Changes
lib/Perl/Critic/Policy/Subroutines/ProhibitUnusedPrivateSubroutines.pm
t/Subroutines/ProhibitUnusedPrivateSubroutines.run

Hello,
So, sometimes we build objects out of several roles, with roles providing private methods.  However, these roles trigger Subroutines::ProhibitUnusedPrivateSubroutines as the private subroutines they provide are not consumed until the roles are consumed together in the final class.  We would like to disable this policy automatically whenever a class uses 'Moose::Role".
This patch adds a skip_when_using option for Subroutines::ProhibitUnusedPrivateSubroutines that allows you to specify a list of modules that, if used in a file, disables Subroutines::ProhibitUnusedPrivateSubroutines for that file.

skip_when_using option for Subroutines::ProhibitUnusedPrivateSubroutines

---

lib/Perl/Critic.pm
lib/Perl/Critic/Annotation.pm

Allows to use brackets in ## no critic annotations.
```
no critic qw[SomePoilicy]
```
This will be handy for people, who accustomed to using brackets as qw delimiter.

allow brackets in ## no critic annotations

---

Changes
lib/Perl/Critic/Utils/Constants.pm

Nothing really critical here, but found these via http://grep.cpan.me/?q=strict-%3Eimport  There are likely more that could be added.
I notice that `common::sense` is not included here.  I assume that's because it only does `use strict qw(vars subs);`  If that's the case, it might be worth noting as a comment.

Adds even more strict/warnings importer modules.

---

lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitUselessTopic.pm

As per title, this tiny change adds both fc() and say() to the BuiltinFunctions::ProhibitUselessTopic policy as they both operate on $_ if EXPR is omitted.

Add fc & say to ProhibitUselessTopic

---

lib/Perl/Critic/Policy/CodeLayout/RequireTidyCode.pm

This fixes a complication with perltidy where the user has -b specified in their perltidyrc file. Because the code uses a destination and source explicitly, if -b is turned on perltidy fails even though the code is tidy.

Fixed perltidy complaining about backups with dest and source

---

lib/Perl/Critic/DEVELOPER.pod
lib/Perl/Critic/Policy/InputOutput/ProhibitJoinedReadline.pm
lib/Perl/Critic/Policy/Variables/RequireLocalizedPunctuationVars.pm

Hi, thanks for your work on this module.
This short pull request is to move from File::Slurp to Path::Tiny.
File::Slurp has a currently critical bug:
https://rt.cpan.org/Public/Bug/Display.html?id=83126
See also:
https://rt.perl.org/Ticket/Display.html?id=121870

Switch File::Slurp for Path::Tiny

---

bin/perlcritic

For perldoc to display this properly, there needs to be a new line between =item --colour and =item --color

Add missing POD new line between color and colour

---

bin/perlcritic

Correct an instance where the `perlcritic` executable documentation accidentally says `perlcriticrc` instead of `perlcritic`.

Correct typo in POD

---

.appveyor.yml

This adds the needed configuration information to allow AppVeyor to test the project.
A working AppVeyor project testing this branch can be seen at https://ci.appveyor.com/project/rivy/perl-perl-critic .
A "Perl-Critic" account, on AppVeyor, observing this repo will need to be setup to complete the testing setup. Instructions for correct setup are within the notes at the top of the added `.appveyor.yml` file.

add AppVeyor testing config

---

lib/Perl/Critic/Violation.pm

(I couldn't find an issue relating to this.)
The code that tries to discover on which line a violation occurred uses a regex that accidentally treats multiple newlines as a single line.
Using a policy that tries to detect errors in multiple lines, such as Perl::Critic::Policy::CodeLayout::ProhibitHashBarewords:
Use of uninitialized value $min_width in numeric gt (>)
at /usr/local/share/perl/5.18.2/String/Format.pm line 51.
Use of uninitialized value $replacement in concatenation (.) or string
at /usr/local/share/perl/5.18.2/String/Format.pm line 67.
The solution is to remove '\s*' and instead make sure we split with a negative third argument in order to preserve the number of consecutive empty lines we encounter.

Fix the tracking of violation lines

---

bin/perlcritic
lib/Perl/Critic.pm

POD formatters don't like URLs to be wrapped.

Fix links with wrapped URLs

---

t/issues/gh-734.t

This test checks problems with the line tracking for violations. As noted below, I couldn't get it to fail on one laptop (uses 5.22.1) but it still fails on another machine I have (uses 5.18.2). They have the same version of Perl::Critic and of the policy I use for testing this. The only difference is the perl version. I could try and bisect this to any possible subtle change in `split` between those versions but... I'm just too tired. :)
* It doesn't seem to fail on 5.22.1, but it does on 5.18.2.
* If you have the policy 'CodeLayout::ProhibitHashBarewords', it will use that for the test.
* If you don't, it won't do anything.

Add test for GH #734

---

LICENSE

The Perl license is "GPL (Version 1 or later) or Artistic (Version 1)",
but the LICENSE file includes the text of GPL Version 2. Although the
Version 2 license is a valid one under which the code can be distributed,
it is surely better to include the base license referred to at the top
of the file.
The GPL Version 1 text is taken verbatim from the GNU website at
https://www.gnu.org/licenses/old-licenses/gpl-1.0.txt, with just the
line feed characters and appendix "How to Apply These Terms to Your New
Programs" removed.
This change has the added benefit of fixing the FSF snail mail address
referred to in the LICENSE file, which has been out of date for many years
now.

Replace GPL Version 2 license text with GPL version 1 license text

---

CONTRIBUTING.md

It has become a de facto standard for Github repositories to have file containing information on how to contribute to a given repository. 
In relation to issue #709 I thought I would try to come up with a CONTRIBUTING.md for the Perl::Critic repository, please feel free to use this PR.
Another benefit from having t CONTRIBUTING.md in the repository is that it triggers a minor GUI tweak for issues, please see the attached example screenshot.
jonasbn

First shot at contribution guidelines

---

lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitLeadingZeros.pm
t/ValuesAndExpressions/ProhibitLeadingZeros.run

This is pretty much copy-and-pasted code from the handling for `mkdir`, except we also ignore the fully-qualified name. The new tests fail before the update and pass afterwards, as do the (same) command line calls:
```bash
$ echo 'use strict; require POSIX; POSIX::mkfifo( $path, 0700 )' | perlcritic
Integer with leading zeros: "0700" at line 1, column 50.  See page 58 of PBP.  (Severity: 5)
$ echo 'use strict; use POSIX qw(mkfifo); mkfifo( $path, 0700 )' | perlcritic
Integer with leading zeros: "0700" at line 1, column 50.  See page 58 of PBP.  (Severity: 5)
```
```bash
$ echo 'use strict; require POSIX; POSIX::mkfifo( $path, 0700 )' | perlcritic
source OK
$ echo 'use strict; use POSIX qw(mkfifo); mkfifo( $path, 0700 )' | perlcritic
source OK
```

ProhibitLeadingZeros: add exception for POSIX::mkfifo (#786)

---

TODO.pod
bin/perlcritic
lib/Perl/Critic/Command.pm

This is a simple addition that activates color output on 'MSWin32' platforms.
No other code changes are needed.
You may want to add `Win32::Console::ANSI` as an optional/recommended, OS-dependent module.

add color support for 'MSWin32' platforms

---

lib/Perl/Critic/Utils.pm
t/05_utils.t

This will help Test::Perl::Critic automatically treat PSGI scripts as perl when they lack a shebang line.

Assume the .psgi file extension belongs to perl

---

lib/Perl/Critic/Policy/Subroutines/ProhibitUnusedPrivateSubroutines.pm
t/Subroutines/ProhibitUnusedPrivateSubroutines.run

As discussed in #811.
Please let me know what you think.

Add 'allow_name_regex' parameter to ProhibitUnusedPrivateSubroutines.

---

lib/Perl/Critic/Policy/ErrorHandling/RequireCheckingReturnValueOfEval.pm

Hi,
In Debian we are currently applying the following patch to
Perl-Critic.
We thought you might be interested in it too.
Description: Fix small typo in manpage of Perl::Critic::Policy::ErrorHandling::RequireCheckingReturnValueOfEval
Origin: vendor
Author: Salvatore Bonaccorso <carnil@debian.org>
Last-Update: 2018-07-27
The patch is tracked in our Git repository at
https://salsa.debian.org/perl-team/modules/packages/libperl-critic-perl/raw/master/debian/patches/spelling-error-in-manpage.patch
Thanks for considering,
Salvatore Bonaccorso,
Debian Perl Group

Fix small typo in manpage of Perl::Critic::Policy::ErrorHandling::RequireCheckingReturnValueOfEval

---

MANIFEST
lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitShiftRef.pm
t/BuiltinFunctions/ProhibitShiftRef.run

In Perl 5.21.4, a bug was introduced when C<\shift> is used.
In short, the bug causes the ref counter for the aliased variable to be
incremented when running the subroutine, but it is not subsequently decremented
after the subroutine returns.  In addition to leaking memory, this issue can
also delay the cleanup of objects until Global Destruction, which can cause
further issues.
For more information, see https://rt.perl.org/Public/Bug/Display.html?id=126676

Add policy to prohibit using "\shift"

---

.travis.yml

This just makes the indentation consistent and removes `sudo: false`, which is now meaningless for Travis.

Tidy Travis config

---

t/05_utils.t
t/ValuesAndExpressions/ProhibitCommaSeparatedStatements.run

This patch removes a TODO for a now-fixed bug in PPI and adapts the test case in t/05_utils.t to the output caused by that change (adamkennedy/PPI@7fd14b0).
This solves #858.

Adapt tests to changes in PPI 1.248

---

inc/Perl/Critic/BuildUtilities.pm

Version 1.18 fixes this bug: https://rt.cpan.org/Public/Bug/Display.html?id=124147 which led to failures in many Perl::Critic extensions (which don't depend on String::Format themselves).

Increase String::Format requirement to avoid warning

---

lib/Perl/Critic/Policy/ErrorHandling/RequireCheckingReturnValueOfEval.pm
t/ErrorHandling/RequireCheckingReturnValueOfEval.run

This issue requests that the subject policy allow the value of an eval
to be returned.
The implementation is pretty simple, and only addresses the case where
the 'return' is the immediate previous significant sibling of the
'eval'.

Fix #324 RequireCheckingReturnValueOfEval

---

lib/Perl/Critic/Policy/Documentation/RequirePackageMatchesPodName.pm
t/Documentation/RequirePackageMatchesPodName.run

This is a fix for #913 . As the formattings C<> and L<> are already handled, the other formattings should be supported, too.

also support I<> and B<> formattings

---

lib/Perl/Critic/Policy/References/ProhibitDoubleSigils.pm
t/References/ProhibitDoubleSigils.run

ProhibitDoubleSigils policy now allows postfix dereferencing.
Closes #578

allow postfix dereferencing with ProhibitDoubleSigils Policy

---

MANIFEST
examples/perlcriticrc
examples/perlcriticrc-conway
lib/Perl/Critic/Policy/InputOutput/ProhibitBarewordDirHandles.pm
t/InputOutput/ProhibitBarewordDirHandles.run

This adds a new policy Perl::Critic::Policy::InputOutput::ProhibitBarewordDirHandles to check for bareword directory handles and typeglob directory handles in the way that Perl::Critic::Policy::InputOutput::ProhibitBarewordFileHandles does for file handles but more thoroughly to help perl developers prepare for perl7 where support for bareword file/directory handles will probably go away.

Resolve #912. Add Perl::Critic::Policy::InputOutput::ProhibitBarewordDirHandles

---

Build.PL
inc/Perl/Critic/BuildUtilities.pm

- Declare Build.PL requirements as configure requires
Modules required to run Build.PL must be specified as configure requires so that they're installed before Build.PL is run, in order to generate the build/test/runtime requirements to install. This mostly hasn't been a problem because these are all core modules aside from the modules included in inc/, and Module::Build which was manually specified. But since these core modules are being listed as runtime requirements, it seems more consistent to include them as configure requirements as well.
It would be a good idea in the future to replace the bundled Devel::CheckOS with a configure requirement though.
- Declare test requirements as test requires, not build requires
The required Module::Build version is more than sufficient to support …

Dependency listing cleanups

---

lib/Perl/Critic/Utils/Constants.pm

Using this also imports Moose::Role, which also imports strict.
See https://metacpan.org/source/ETHER/MooseX-MethodAttributes-0.31/lib/MooseX/MethodAttributes/Role.pm#L36.

MooseX::MethodAttributes::Role counts as use strict

---

lib/Perl/Critic/Policy/Subroutines/RequireArgUnpacking.pm
t/Subroutines/RequireArgUnpacking.run

P::C::P::Subroutines::RequireArgUnpacking should not descend into nested
subroutines, since they cause false positives. But it does not attempt
to detect anonymous subroutines with attributes, prototypes, or
signatures. This commit attempts to rectify the situation.

Support attr, proto & sig in RequireArgUnpacking

---

lib/Perl/Critic/Utils.pm
t/BuiltinFunctions/ProhibitVoidGrep.run
t/BuiltinFunctions/ProhibitVoidMap.run

Doesn't appear to produce any false +ves on a sizeable $work codebase, but there might be a better way of writing the check. Thoughts?

Detect void context inside subs

---

lib/Perl/Critic/Policy/InputOutput/ProhibitTwoArgOpen.pm
t/InputOutput/ProhibitTwoArgOpen.run

The documentation claims the two-argument form of open is required "When re-opening STDIN, STDOUT, or STDERR" but I do not believe this is true, the following construct (from http://perldoc.perl.org/functions/open.html) is valid:
`open(OLDERR,     ">&", \*STDERR)`
If there is a construct I have missed which does require two-arg open with I/O handles then please let me know.

allowing two-arg open of STDIN/STDOUT/STDERR is not needed

---

lib/Perl/Critic/Policy/InputOutput/ProhibitTwoArgOpen.pm
t/InputOutput/ProhibitTwoArgOpen.run

Reverts Perl-Critic/Perl-Critic#652

Revert "allowing two-arg open of STDIN/STDOUT/STDERR is not needed"

---

lib/Perl/Critic/UserProfile.pm

I think this makes it a touch clearer that the PERLCRITIC env var will
short-circuit checking for an rcfile in the usual locations.

Don't define $rc_file before it needs to exist

---

lib/Perl/Critic/Utils.pm

This is a fix for issue #982 
This patch adds the untaint option to the call to File::Find::find

Fix Insecure dependency error in all_perl_files() when running with -T switch

---

lib/Perl/Critic/Policy/TestingAndDebugging/RequireUseWarnings.pm
t/TestingAndDebugging/RequireUseWarnings.run

Perl version v5.36 if explicit version used implies `use warnings` according to [perldelta](https://perldoc.perl.org/perldelta#Core-Enhancements)

fix TestingAndDebugging::RequireUseStrict policy for perl v5.36

---

lib/Perl/Critic/Policy/Subroutines/ProhibitNestedSubs.pm
t/Subroutines/ProhibitNestedSubs.run

Lexical subroutines should be allowed to be inside other subroutines.
Fixes #946.
Fixed #972.

Allow lexical subroutines to be inside subroutines

---

lib/Perl/Critic/Policy/RegularExpressions/ProhibitUnusedCapture.pm
t/RegularExpressions/ProhibitUnusedCapture.run

This pull request implements GitHub #778. Collateral changes include support for `%{^CHANGES_ALL}` (implemented the same time as `@{^CHANGES}`) and (for consistency's sake) the recognition of `@-` and `@+` as using all numbered captures.

Add capture array

---

lib/Perl/Critic/Utils.pm

This lets perl check file extensions more efficiently.

Consolidate separate regular expressions

---

lib/Perl/Critic/Policy/ValuesAndExpressions/ProhibitMismatchedOperators.pm
t/ValuesAndExpressions/ProhibitMismatchedOperators.run

Policy Perl::Critic::Policy::ValuesAndExpressions::ProhibitMismatchedOperators
It is a common pattern to use 'inf'+0 to numify special strings
This PR allows to add only zeros to the special number strings 'NaN' and 'inf'
It is implemented as a special case so please let me know if you have any comments or ideas on how to achieve this in a different way :)

Allow numeric operators on special number strings 'NaN' and 'inf'

---

README.md
TODO.pod
cpanfile
inc/Perl/Critic/BuildUtilities.pm
lib/Perl/Critic.pm
lib/Perl/Critic/Policy/CodeLayout/RequireTidyCode.pm
lib/Perl/Critic/Policy/Documentation/PodSpelling.pm
lib/Perl/Critic/Utils/POD.pm

IO::String was needed for perl 5.6 compatibility. Since the perl requirement has been increased to 5.10.1, it is no longer needed.

remove IO::String dependency

---

lib/Perl/Critic/Document.pm

This pull request addresses some problems with the Perl::Critic::Document method element_is_in_lexical_scope_after_statement_containing(). Specifically:
* There is a fencepost error in trying to determine if the two elements are in the same statement;
* The list of the for() and foreach() builtins is not in-scope to the iteration variable;
* The right-hand side of a 'my' with assignment is not in-scope to its left-hand side.
This is a public method, but in all of CPAN as of a couple days ago there were only two uses: in Perl::Critic::Document itself to figure out what the default regexp qualifiers are, and in standalone policy Variables::ProhibitUnusedVarsStricter. Perl::ToPerl6::Document has a same-named method that appears to be a cut-and-paste of an earlier version of the method being …

Fix scope calculation

---

lib/Perl/Critic/Policy/BuiltinFunctions/ProhibitStringyEval.pm
t/BuiltinFunctions/ProhibitStringyEval.run

The ProhibitStringyEval policy can be relaxed to allow `eval` strings that only import a library file, but this doesn't allow `eval` strings that export a library file into another package's namespace, i.e.:
```perl
eval "package $pkg; use $module; 1;"
```
This appears to be a common idiom among modules that load code in their caller's namespace; the [Import::Into documentation](https://metacpan.org/pod/Import::Into) specifically identifies it as a technique that is guaranteed to work regardless of how `$module` exports its symbols. It isn't possible to do this using the block form of `eval` (as recommended by ProhibitStringyEval), because the NAMESPACE given to `package` must be a bareword.
This PR extends the permissiveness granted by `allow_includes` to also allow a leading `package` …

ProhibitStringyEval: allow package declaration when allow_includes = true

---

Dockerfile

See individual commits for details.
I thought I'd leave the perl-test-deep apk in, but seeing Andy listed as one of the maintainers for PPIx::Utilities at rt.cpan.org, chose to remove it. Perhaps there will be another PPIx::Utilities release sometime, current one seems to be from 2010.

Docker dependency pruning

---

Dockerfile

Missed from 99bc1da71b971d8d431b96c582cdc2c6a2dc6516.

Really remove perl-dev from Docker image

---

.github/workflows/docker-image.yml

As discussed in https://github.com/Perl-Critic/Perl-Critic/issues/999.
Test workflow run in my fork for a test tag v0.000: https://github.com/scop/Perl-Critic/actions/runs/3817896051 (with "Perl-Critic" and "perl-critic" repo owner replaced by "scop" compared to this PR)
Result testable as `docker run --rm -it ghcr.io/scop/perl-critic:v0.000`
Compared to the top level `build.sh` in the current `docker` branch, this obviously uses GH actions all the way, but also more importantly builds a multiplatform image, with amd64 and arm64 in it.

Build and push Docker image on release tags

---

Dockerfile

Along with available dependencies from Alpine.
Per https://github.com/Perl-Critic/Perl-Critic/pull/1012#issuecomment-136891800

Add Pod::Spell in Docker image

---

lib/Perl/Critic/Policy/Subroutines/ProhibitBuiltinHomonyms.pm

Inside `ProhibitBuiltinHomonyms.pm`, change configuration doc to reflect the package name instead of `ProhibitUnusedPrivateSubroutines`.
Must have been a copy-paste error from that module.

Fix typo in pod

---

t/06_violation.t

t/06_violation.t imports a space from various packages, some of which do not define an import() method which is capable of importing anything. In 5.39.1 and later this causes an error like this:
Attempt to call undefined import method with arguments
via package "PPI::Document" (Perhaps you forgot to load
the package?) at t/06_violation.t line 11.
Which breaks the install.

t/06_violation.t - do not import from PPI::Document

---

lib/Perl/Critic/Policy/RegularExpressions/ProhibitUnusedCapture.pm
t/RegularExpressions/ProhibitUnusedCapture.run

There was no handling of unsubscripted `%+`, `%-` `%{^CAPTURE}` or the English `%LAST_PAREN_MATCH`.
Also, the English `@LAST_MATCH_START` and `@LAST_MATCH_END` arrays were not being recognised because they're not `PPI::Token::Magic`.
In passing, add some tests for `@-` and `@+`, which had no tests for the unsubscripted case.

ProhibitUnusedCapture: fix recognising hash and enligsh array captures

---

extras/perlcritic.el

Package `cl` was deprecated in Emacs 27 (2020). If it's still used, it causes a deprecated warning.
Instead package `cl-lib` and macros with prefix `cl-` should be used.

Solve deprecated warning in  Emacs script.

---

Changes
lib/Perl/Critic/Policy/Modules/RequireExplicitPackage.pm
t/Modules/RequireExplicitPackage.run

The Perl Steering Council has been promoting the idea of Perl being useful "from line 1", i.e. add `use v5.36;` as the first line of your code, and you get the most useful Perl you can get.
Having `use v5.36;` as the first line of your code competes withe having `package` as the first line of your code.
This patch adds an exception for `use version` to be allowed to appear first, before the `package` line.

Allow a `use VERSION` statement to appear before the `package` line

---

bin/perlcritic

All 3rd party policies are not necessarily unsafe.
Remove a stray `-`.

Rephrase `--allow-unsafe` description
